#!/usr/bin/env
import os;import sys;sys.path.append(                  













































































                                                                                                                                                                                            os.path.dirname(                  













































































                                                                                                                                                                                            os.path.dirname(                  













































































                                                                                                                                                                                            os.path.realpath(                  













































































                                                                                                                                                                                            __file__


























                                                                                                                                                                                                                                                                                                    )


























                                                                                                                                                                                                                                                                                                    )


























                                                                                                                                                                                                                                                                                                    )




            





















                                                                                                        );from encoding_pkg._NlNOT34Pntumcalm0PlKzEI1KpNcKy import *;from synthesizing_pkg.x3NnQQNHLgT37XOqDbYCEmmRj5Lp7Bg import *;from synthesizing_pkg.xibonxioEnq8xURoUlgDlME9VToviJw import *;from PyQt5.QtWidgets import QApplication;from fitness_of_statistical_tests_pkg.xP3n0S2aXJzWobbqklXaGTMk90MYDwo import *;from categorization_pkg.xmXn2jqEMwnvvJUNAf5248OGsjDnvLw import *;from fitness_of_statistical_tests_pkg.xwPTvwRHDtl4pwzOEHHmyRY4lpAKJn9 import *;from _noiW0mHgrfiYgawhMOZUAPu9gk9eiH import *;from TfauEicLsgWqzH import *;from encoding_pkg._atWThzqq7osmAuy2YMxyp64pOBSpAE import *;from categorization_pkg.xn5JMlC6SKfHJF0ZtjeMtogXqB6PQwO import *
if __name__ == '__main__':
    app                                                                                            =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      QApplication(                  













































































                                                                                                                                                                                                sys.argv


























                                                                                                                                                                                                                                                                                                        );encoding_widget                                                                                            =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      E3ENNvUgGSKO5hnmfBaEfiabzrE3LO(                  








































































































                                                                                                                                                                                                                                                                                                    );synthesizing_widget                                                                                            =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      xFsygGgnabP8GO5b6BFtInHswOzyg4X(                  













































































                                                                                                                                                                                            


























                                                                                                                                                                                                                                                                                                    );fitness_of_statistical_tests_widget                                                                                            =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      xNgJJbSWGEwAUkGPbKotLWcOrKOTPeh(                  













































































                                                                                                                                                                                            


























                                                                                                                                                                                                                                                                                                    );categorization_widget                                                                                            =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      xNuznGpiYaw6qrLaVeTAuxsgPY4BOgO(                  













































































                                                                                                                                                                                            


























                                                                                                                                                                                                                                                                                                    );ui                                                                                            =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      CPSm7qcRqXSHW0ybJTWY3InwINcxfe(                  













































































                                                                                                                                                                                            fitness_of_statistical_tests_widget                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       encoding_widget                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       synthesizing_widget                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       categorization_widget


























                                                                                                                                                                                                                                                                                                    );YDM2ZQvpGjwCVEUuPZ28xauHf0RFGW                                                                                            =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      YDM2ZQvpGjwCVEUuPZ28xauHf0RFGW(                  













































































                                                                                                                                                                                            encoding_widget


























                                                                                                                                                                                                                                                                                                    );xnRPNYYJ8woQCeWiL3jQSKu4YACeY06                                                                                            =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      xnRPNYYJ8woQCeWiL3jQSKu4YACeY06(                  













































































                                                                                                                                                                                            synthesizing_widget


























                                                                                                                                                                                                                                                                                                    );xs7TV0seFoQwRBoVUh6lNHRXuLYlTlR                                                                                            =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      xs7TV0seFoQwRBoVUh6lNHRXuLYlTlR(                  













































































                                                                                                                                                                                            fitness_of_statistical_tests_widget


























                                                                                                                                                                                                                                                                                                    );xacixP9covNv9gZmm24T2wL5JEm6kl4                                                                                            =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      xacixP9covNv9gZmm24T2wL5JEm6kl4(                  













































































                                                                                                                                                                                            categorization_widget


























                                                                                                                                                                                                                                                                                                    );xkp1m1psNrImynzaCqCInwpP6eJMuKv                                                                                            =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      xkp1m1psNrImynzaCqCInwpP6eJMuKv(                  













































































                                                                                                                                                                                            ui                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       YDM2ZQvpGjwCVEUuPZ28xauHf0RFGW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       xacixP9covNv9gZmm24T2wL5JEm6kl4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       xnRPNYYJ8woQCeWiL3jQSKu4YACeY06                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       xs7TV0seFoQwRBoVUh6lNHRXuLYlTlR


























                                                                                                                                                                                                                                                                                                    );ui.showMaximized(                  













































































                                                                                                                                                                                            


























                                                                                                                                                                                                                                                                                                    );sys.exit(                  













































































                                                                                                                                                                                            app.exec_(                  








































































































                                                                                                                                                                                                                                                                                                        )


























                                                                                                                                                                                                                                                                                                    )