#!/usr/bin/env
from PyQt5.QtCore import QObject
class xkp1m1psNrImynzaCqCInwpP6eJMuKv(





















































                                                                                                                                                                                                                                                                                                     QObject





































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ):
    def __init__(





















































                                                                                                                                                                                                                                                                                                         self


        ,















                                                                                                                                                                                                                                                                     fnvqSKNyvxBYAl


        ,















                                                                                                                                                                                                                                                                     RfXXffqfDwgraq


        ,















                                                                                                                                                                                                                                                                     DTYEhBItkXkYXm


    ,















                                                                                                                                                                                                                                                                 pSDwcUhkYwOWhW


    ,















                                                                                                                                                                                                                                                                 LjqGFoqRULpeHR





































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ):
        super(





















































                                                                                                                                                                                                                                                                                                             xkp1m1psNrImynzaCqCInwpP6eJMuKv


            ,















                                                                                                                                                                                                                                                                         self





































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ).__init__(



























































































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );self.iK_yMagGSDShIj                                                                                                                                                                                    =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fnvqSKNyvxBYAl;self.FSwReWSBzMkGYt                                                                                                                                                                                    =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      DTYEhBItkXkYXm;self.ncPqmwbCiAiVoS                                                                                                                                                                                    =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      RfXXffqfDwgraq;self.sJgRIbDGQyDjof                                                                                                                                                                                    =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      LjqGFoqRULpeHR;self.ScnsrgKQAzwuan                                                                                                                                                                                    =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pSDwcUhkYwOWhW;self.iK_yMagGSDShIj._skSSVTFaw5aXmIQh26M3ojWvMhHJ0B.clicked.connect(





















































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         self.ncPqmwbCiAiVoS._aQFCjrxYh6ARAPVPu0ZJE7awr0JK8a





































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );self.iK_yMagGSDShIj._XgJJg2pKMxqa2DnzP2NSlVCKwTh2TA.currentChanged.connect(





















































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         self.reconnect_help_button





































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
    def reconnect_help_button(





















































                                                                                                                                                                                                                                                                                                         self


        ,















                                                                                                                                                                                                                                                                     tvpSSsiUTphhBh





































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ):
        self.iK_yMagGSDShIj._skSSVTFaw5aXmIQh26M3ojWvMhHJ0B.clicked.disconnect(



























































































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
        if tvpSSsiUTphhBh                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ==                                                                        0: self.iK_yMagGSDShIj._skSSVTFaw5aXmIQh26M3ojWvMhHJ0B.clicked.connect(





















































                                                                                                                                                                                                                                                                                                             self.ncPqmwbCiAiVoS._aQFCjrxYh6ARAPVPu0ZJE7awr0JK8a





































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
        if tvpSSsiUTphhBh                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ==                                                                        1: self.iK_yMagGSDShIj._skSSVTFaw5aXmIQh26M3ojWvMhHJ0B.clicked.connect(





















































                                                                                                                                                                                                                                                                                                             self.FSwReWSBzMkGYt._XxoDMDM1A9zSUt3PF0szty1PlTpAli





































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
        if tvpSSsiUTphhBh                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ==                                                                        2: self.iK_yMagGSDShIj._skSSVTFaw5aXmIQh26M3ojWvMhHJ0B.clicked.connect(





















































                                                                                                                                                                                                                                                                                                             self.ScnsrgKQAzwuan._AJ2UrEl6PJrnnTVxBHa8l0pfHFe2qU





































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
        if tvpSSsiUTphhBh                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ==                                                                        3: self.iK_yMagGSDShIj._skSSVTFaw5aXmIQh26M3ojWvMhHJ0B.clicked.connect(





















































                                                                                                                                                                                                                                                                                                             self.sJgRIbDGQyDjof._H5BkWqrO1zO8VSABHF7eCKAEAgs2PK





































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
