#!/usr/bin/env

from PyQt5 import QtWidgets;import matplotlib;matplotlib.use(




























                                                                                                                                                       "Qt5Agg"
































































                                                                                                                                                                                                                                                                                                                                                                                                                                    );from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as _n3BhXH513lu8nvKLjWiMxrwQM1tWMa;from matplotlib.figure import Figure

class ATVjocfOmkVVnPOX8kwk9Sot6FrQs0(




























                                                                                                                                                       _n3BhXH513lu8nvKLjWiMxrwQM1tWMa
































































                                                                                                                                                                                                                                                                                                                                                                                                                                    ):
    def __init__(




























                                                                                                                                                           self                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                      _3umTg7ivjSBZz6BEf9IeSCzWKCpjG8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                      _PyJnfpPua5t0yiHt0bHGzGD2y774vD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                      _TIgf0IFOAlqBROHEQSxuVIorNQp0FS=None                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                      _MWfc0eJmkF8F4PlF7F12hjov3TAIql=None                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                     _jUaScHTSOiDYCtwa9BBGbWj9DmgkYu=None
































































                                                                                                                                                                                                                                                                                                                                                                                                                                        ):
        _wHVwMxn9qU48ABckK1ZeNO6ZTzW5P7 = Figure(





























































































                                                                                                                                                                                                                                                                                                                                                                                                                                            );self.axes = _wHVwMxn9qU48ABckK1ZeNO6ZTzW5P7.add_subplot(




























                                                                                                                                                               111
































































                                                                                                                                                                                                                                                                                                                                                                                                                                            );_n3BhXH513lu8nvKLjWiMxrwQM1tWMa.__init__(




























                                                                                                                                                               self                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                      _wHVwMxn9qU48ABckK1ZeNO6ZTzW5P7
































































                                                                                                                                                                                                                                                                                                                                                                                                                                            );self.setParent(




























                                                                                                                                                               _jUaScHTSOiDYCtwa9BBGbWj9DmgkYu
































































                                                                                                                                                                                                                                                                                                                                                                                                                                            );self.axes.boxplot(




























                                                                                                                                                           _PyJnfpPua5t0yiHt0bHGzGD2y774vD
































































                                                                                                                                                                                                                                                                                                                                                                                                                                        );self.axes.set_ylabel(




























                                                                                                                                                           "GWF"
































































                                                                                                                                                                                                                                                                                                                                                                                                                                        );self.axes.yaxis.grid(




























                                                                                                                                                           True                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                      linestyle='-'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                      which='major'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                      color='lightgrey'
































































                                                                                                                                                                                                                                                                                                                                                                                                                                        )
        if _TIgf0IFOAlqBROHEQSxuVIorNQp0FS:
            if _TIgf0IFOAlqBROHEQSxuVIorNQp0FS[1] != _TIgf0IFOAlqBROHEQSxuVIorNQp0FS[0]:
                self.axes.set_ylim(




























                                                                                                                                                                       [_TIgf0IFOAlqBROHEQSxuVIorNQp0FS[0]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                     _TIgf0IFOAlqBROHEQSxuVIorNQp0FS[1]]
































































                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
        if _MWfc0eJmkF8F4PlF7F12hjov3TAIql:
            self.axes.set_yscale(




























                                                                                                                                                                   _MWfc0eJmkF8F4PlF7F12hjov3TAIql
































































                                                                                                                                                                                                                                                                                                                                                                                                                                                )
        self.axes.set_xlabel(




























                                                                                                                                                               "Regex"
































































                                                                                                                                                                                                                                                                                                                                                                                                                                            );self.axes.set_xticks(




























                                                                                                                                                               range(




























                                                                                                                                                                   1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                     len(




























                                                                                                                                                                       _3umTg7ivjSBZz6BEf9IeSCzWKCpjG8
































































                                                                                                                                                                                                                                                                                                                                                                                                                                                    )+1
































































                                                                                                                                                                                                                                                                                                                                                                                                                                                )
































































                                                                                                                                                                                                                                                                                                                                                                                                                                            );self.axes.set_xticklabels(




























                                                                                                                                                               _3umTg7ivjSBZz6BEf9IeSCzWKCpjG8
































































                                                                                                                                                                                                                                                                                                                                                                                                                                            );self.axes.hold(




























                                                                                                                                                               False
































































                                                                                                                                                                                                                                                                                                                                                                                                                                            )
        _n3BhXH513lu8nvKLjWiMxrwQM1tWMa.setSizePolicy(




























                                                                                                                                                               self                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                     
                QtWidgets.QSizePolicy.Preferred                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,                                                                                                                                                                                                                                                                                                                                                     
                QtWidgets.QSizePolicy.Preferred
































































                                                                                                                                                                                                                                                                                                )
        _n3BhXH513lu8nvKLjWiMxrwQM1tWMa.updateGeometry(




























                                                                                                                                                               self
































































                                                                                                                                                                                                                                                                                                                                                                                                                                            )
