#!/usr/bin/env
import csv as _mzE5jXyPh0zJEGqEeqGkVruwgp9wQj;from datetime import datetime as _9FMlrH7GIQLPHK0NivP799cKP1Ntbx;import os as _g8vxurv8oI28h5ggfYGUEbaDMktLNM;import sys as _xSkebvTPAT2XkcWqPBHEvHJ8jTXgce;import numpy as _gHyvKBS3AGk4Y60tCpmRFasYwMjS5O;_xSkebvTPAT2XkcWqPBHEvHJ8jTXgce.path.append(























                                                                                                                                                                                                _g8vxurv8oI28h5ggfYGUEbaDMktLNM.path.dirname(























                                                                                                                                                                                                    _g8vxurv8oI28h5ggfYGUEbaDMktLNM.path.dirname(























                                                                                                                                                                                                        _g8vxurv8oI28h5ggfYGUEbaDMktLNM.path.realpath(























                                                                                                                                                                                                            __file__




















                                                                                                                                                                                                                                                                ))




















                                                                                                                                                                                                                                                        ))
def _aAaXyupVqOtCI9TfLPkRK5NKbNms5U(























                                                                                                                                                                                                _q70pzYD86yx8eG54YvKLKWM0ZoWz24, _3PnFc1IcAHyRIuvvapDXLnx17weASv




















                                                                                                                                                                                                                                                    ):
    _aYUwXytMQLUEqp95X28yjiomKl6eqM                                                        =                                                                                                  []
    _PGxEKQ5Svew4DGc0Mliq4ZF6A13NFC                                                        =                                                                                                  _mh2lIrvtp5H93pf9F1rruMBQggmLDg(























                                                                                                                                                                                                    _q70pzYD86yx8eG54YvKLKWM0ZoWz24




















                                                                                                                                                                                                                                                        )
    for _QHh7QzyXfbMolkEsOw539rMnG9IQml in     _PGxEKQ5Svew4DGc0Mliq4ZF6A13NFC:
        for _XV7JaDvc1q2C12LTqecQm0qlAxlJkG in         _QHh7QzyXfbMolkEsOw539rMnG9IQml:
            if _XV7JaDvc1q2C12LTqecQm0qlAxlJkG is not '':
                _aYUwXytMQLUEqp95X28yjiomKl6eqM.append(























                                                                                                                                                                                                                float(























                                                                                                                                                                                                                    _XV7JaDvc1q2C12LTqecQm0qlAxlJkG




















                                                                                                                                                                                                                                                                        ))
    _aYUwXytMQLUEqp95X28yjiomKl6eqM                                                        =                                                                                                  _gHyvKBS3AGk4Y60tCpmRFasYwMjS5O.array(























                                                                                                                                                                                                    _aYUwXytMQLUEqp95X28yjiomKl6eqM




















                                                                                                                                                                                                                                                        )
    _aYUwXytMQLUEqp95X28yjiomKl6eqM                                                        =                                                                                                  _aYUwXytMQLUEqp95X28yjiomKl6eqM.astype(























                                                                                                                                                                                                    int




















                                                                                                                                                                                                                                                        )
    _Rw22oOK23PNoWutV4za789pVt3hBLL                                                        =                                                                                                  []
    for _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG in     range(























                                                                                                                                                                                                    1, _3PnFc1IcAHyRIuvvapDXLnx17weASv+1




















                                                                                                                                                                                                                                                        ):
        _Rw22oOK23PNoWutV4za789pVt3hBLL.append(























                                                                                                                                                                                                        round(























                                                                                                                                                                                                            _gHyvKBS3AGk4Y60tCpmRFasYwMjS5O.percentile(























                                                                                                                                                                                                                _aYUwXytMQLUEqp95X28yjiomKl6eqM,
                                                 _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG * 100/_3PnFc1IcAHyRIuvvapDXLnx17weASv




















                                                                                                    ))




















                                                                                                                                                                                                                                                            )
    _xPES9fUvCOAfvncOMz5R1axtMllRMo                                                        =                                                                                                  'A'
    _Re4e2NCPKcSjCnC9R6MDTXwK8SDoMH                                                        =                                                                                                  _gHyvKBS3AGk4Y60tCpmRFasYwMjS5O.amin(























                                                                                                                                                                                                    _aYUwXytMQLUEqp95X28yjiomKl6eqM




















                                                                                                                                                                                                                                                        )
    _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E                                                        =                                                                                                  {}
    for _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG in     range(























                                                                                                                                                                                                    0, _3PnFc1IcAHyRIuvvapDXLnx17weASv




















                                                                                                                                                                                                                                                        ):
        if _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG is 0:
            _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E[chr(























                                                                                                                                                                                                            ord(























                                                                                                                                                                                                                _xPES9fUvCOAfvncOMz5R1axtMllRMo




















                                                                                                                                                                                                                                                                    )                                                                                                   +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG




















                                                                                                                                                                                                                                                                )]                                                        =                                                                                                                  [_gHyvKBS3AGk4Y60tCpmRFasYwMjS5O.int16(























                                                                                                                                                                                                        _Re4e2NCPKcSjCnC9R6MDTXwK8SDoMH




















                                                                                                                                                                                                                                                            ), _gHyvKBS3AGk4Y60tCpmRFasYwMjS5O.int16(























                                                                                                                                                                                                        _Rw22oOK23PNoWutV4za789pVt3hBLL[_b3Q9bROj5pxEa2A6K4QugeFYv6tUNG]




















                                                                                                                                                                                                                                                            )]
        elif _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG is _3PnFc1IcAHyRIuvvapDXLnx17weASv-1:
            _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E[chr(























                                                                                                                                                                                                            ord(























                                                                                                                                                                                                                _xPES9fUvCOAfvncOMz5R1axtMllRMo




















                                                                                                                                                                                                                                                                    )                                                                                                   +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG




















                                                                                                                                                                                                                                                                )]                                                        =                                                                                                                  [_gHyvKBS3AGk4Y60tCpmRFasYwMjS5O.int16(























                                                                                                                                                                                                        _Rw22oOK23PNoWutV4za789pVt3hBLL[_b3Q9bROj5pxEa2A6K4QugeFYv6tUNG-1]




















                                                                                                                                                                                                                                                            ), _gHyvKBS3AGk4Y60tCpmRFasYwMjS5O.int16(























                                                                                                                                                                                                        _Rw22oOK23PNoWutV4za789pVt3hBLL[_b3Q9bROj5pxEa2A6K4QugeFYv6tUNG]




















                                                                                                                                                                                                                                                            )+1]
        else:
            _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E[chr(























                                                                                                                                                                                                            ord(























                                                                                                                                                                                                                _xPES9fUvCOAfvncOMz5R1axtMllRMo




















                                                                                                                                                                                                                                                                    )                                                                                                   +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG




















                                                                                                                                                                                                                                                                )]                                                        =                                                                                                                  [_gHyvKBS3AGk4Y60tCpmRFasYwMjS5O.int16(























                                                                                                                                                                                                        _Rw22oOK23PNoWutV4za789pVt3hBLL[_b3Q9bROj5pxEa2A6K4QugeFYv6tUNG-1]




















                                                                                                                                                                                                                                                            ), _gHyvKBS3AGk4Y60tCpmRFasYwMjS5O.int16(























                                                                                                                                                                                                        _Rw22oOK23PNoWutV4za789pVt3hBLL[_b3Q9bROj5pxEa2A6K4QugeFYv6tUNG]




















                                                                                                                                                                                                                                                            )]
    return _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E
def _VErYRFcVfzUsaoOPmiVSBfpZ701U0Q(























                                                                                                                                                                                                _q70pzYD86yx8eG54YvKLKWM0ZoWz24




















                                                                                                                                                                                                                                                    ):
    _PGxEKQ5Svew4DGc0Mliq4ZF6A13NFC                                                        =                                                                                                  _mh2lIrvtp5H93pf9F1rruMBQggmLDg(























                                                                                                                                                                                                    _q70pzYD86yx8eG54YvKLKWM0ZoWz24




















                                                                                                                                                                                                                                                        )
    _aYUwXytMQLUEqp95X28yjiomKl6eqM                                                        =                                                                                                  []
    for _LHeQPgLLUNVv8lwUXLB0hEGTcFD1v4 in     _PGxEKQ5Svew4DGc0Mliq4ZF6A13NFC:
        _aYUwXytMQLUEqp95X28yjiomKl6eqM                                                         +=                                                                                                                                       [_XV7JaDvc1q2C12LTqecQm0qlAxlJkG.strip(























                                                                                                                                                                                                        ' ').lower(












































                                                                                                                                                                                                                                                            ) for _XV7JaDvc1q2C12LTqecQm0qlAxlJkG in         _LHeQPgLLUNVv8lwUXLB0hEGTcFD1v4]
    _4eXMRFD5j3hnTu68f1aYjU2yTkuncX                                                        =                                                                                                  _gHyvKBS3AGk4Y60tCpmRFasYwMjS5O.unique(























                                                                                                                                                                                                    _aYUwXytMQLUEqp95X28yjiomKl6eqM




















                                                                                                                                                                                                                                                        )
    _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E                                                        =                                                                                                  {}
    _xPES9fUvCOAfvncOMz5R1axtMllRMo                                                        =                                                                                                  'A'
    _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG                                                        =                                                                                                  0
    while _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG < len(























                                                                                                                                                                                                    _4eXMRFD5j3hnTu68f1aYjU2yTkuncX




















                                                                                                                                                                                                                                                        ):
        _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E[chr(























                                                                                                                                                                                                        ord(























                                                                                                                                                                                                            _xPES9fUvCOAfvncOMz5R1axtMllRMo




















                                                                                                                                                                                                                                                                )                                                                                                   +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG




















                                                                                                                                                                                                                                                            )]                                                        =                                                                                                  _4eXMRFD5j3hnTu68f1aYjU2yTkuncX[_b3Q9bROj5pxEa2A6K4QugeFYv6tUNG]
        _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG                                                         +=                                                                                                                                       1
    return _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E
def _vtaTe6YhRPCpqwwSU9BRqkpIZcQ5xt(























                                                                                                                                                                                                _CttQ6tHbcklk8pE62XKYDbOeSJluK1, _fRCKK0801ssk2Cz1as9z9AEOeCKnSV




















                                                                                                                                                                                                                                                    ):
    for _cZw5n8CMFTIlfNEjpt2hcb6wx9inUs in     _CttQ6tHbcklk8pE62XKYDbOeSJluK1:
        _FWGbavG23Dm9TSOe6Kro5bHk8qHHyk                                                        =                                                                                                  _CttQ6tHbcklk8pE62XKYDbOeSJluK1[_cZw5n8CMFTIlfNEjpt2hcb6wx9inUs]
        if int(























                                                                                                                                                                                                        float(























                                                                                                                                                                                                            _fRCKK0801ssk2Cz1as9z9AEOeCKnSV




















                                                                                                                                                                                                                                                                )) >= _FWGbavG23Dm9TSOe6Kro5bHk8qHHyk[0] and int(























                                                                                                                                                                                                    float(























                                                                                                                                                                                                        _fRCKK0801ssk2Cz1as9z9AEOeCKnSV




















                                                                                                                                                                                                                                                            )) < _FWGbavG23Dm9TSOe6Kro5bHk8qHHyk[1]:
            return _cZw5n8CMFTIlfNEjpt2hcb6wx9inUs
    raise ValueError(























                                                                                                                                                                                                    "replacenumber error"




















                                                                                                                                                                                                                                                        )
def _mh2lIrvtp5H93pf9F1rruMBQggmLDg(























                                                                                                                                                                                                _QI2atZFwNrUKNkS7c6RDy6Xa7014MR




















                                                                                                                                                                                                                                                    ):
    _0ulWv02YpDSKo7HjYBOtHPBLfE9mY0                                                        =                                                                                                  open(























                                                                                                                                                                                                    _QI2atZFwNrUKNkS7c6RDy6Xa7014MR, 'r').read(












































                                                                                                                                                                                                                                                        ).splitlines(












































                                                                                                                                                                                                                                                        )
    _3E6t1N3elD6ca304WQV7J5HzXKAXCH                                                        =                                                                                                  []
    for _QHh7QzyXfbMolkEsOw539rMnG9IQml in     _0ulWv02YpDSKo7HjYBOtHPBLfE9mY0:
        _3E6t1N3elD6ca304WQV7J5HzXKAXCH.append(























                                                                                                                                                                                                        _QHh7QzyXfbMolkEsOw539rMnG9IQml.replace(























                                                                                                                                                                                                            ',',' ').split(












































                                                                                                                                                                                                                                                                )[:-1]




















                                                                                                                                                                                                                                                                )
    return _3E6t1N3elD6ca304WQV7J5HzXKAXCH
def _3E6t1N3elD6ca304WQV7J5HzXKAXCH(























                                                                                                                                                                                                _QI2atZFwNrUKNkS7c6RDy6Xa7014MR, _CttQ6tHbcklk8pE62XKYDbOeSJluK1




















                                                                                                                                                                                                                                                    ):
    _0ulWv02YpDSKo7HjYBOtHPBLfE9mY0                                                        =                                                                                                  _mh2lIrvtp5H93pf9F1rruMBQggmLDg(























                                                                                                                                                                                                    _QI2atZFwNrUKNkS7c6RDy6Xa7014MR




















                                                                                                                                                                                                                                                        )
    _6s2pxP8Fxy0cKno3NrgIeiF65WOYHH                                                        =                                                                                                  []
    _aYUwXytMQLUEqp95X28yjiomKl6eqM                                                        =                                                                                                  []
    for _LHeQPgLLUNVv8lwUXLB0hEGTcFD1v4 in     _0ulWv02YpDSKo7HjYBOtHPBLfE9mY0:
        _aYUwXytMQLUEqp95X28yjiomKl6eqM.append(























                                                                                                                                                                                                        _LHeQPgLLUNVv8lwUXLB0hEGTcFD1v4




















                                                                                                                                                                                                                                                            )
    for _3L2XfZmAA6iLMULntLjAf6Cjx0caHA in     _aYUwXytMQLUEqp95X28yjiomKl6eqM:
        _RFje3WVt3cPYPJiYn2xcit2oPpfxWe                                                        =                                                                                                  0
        _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E                                                        =                                                                                                  ''
        while _RFje3WVt3cPYPJiYn2xcit2oPpfxWe < len(























                                                                                                                                                                                                        _3L2XfZmAA6iLMULntLjAf6Cjx0caHA




















                                                                                                                                                                                                                                                            ):
            for _cZw5n8CMFTIlfNEjpt2hcb6wx9inUs in             _CttQ6tHbcklk8pE62XKYDbOeSJluK1:
                if _3L2XfZmAA6iLMULntLjAf6Cjx0caHA[_RFje3WVt3cPYPJiYn2xcit2oPpfxWe].strip(























                                                                                                                                                                                                                ' ').lower(












































                                                                                                                                                                                                                                                                    ) == _CttQ6tHbcklk8pE62XKYDbOeSJluK1[_cZw5n8CMFTIlfNEjpt2hcb6wx9inUs]:
                    _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E                                                         +=                                                                                                                                       _cZw5n8CMFTIlfNEjpt2hcb6wx9inUs
            _RFje3WVt3cPYPJiYn2xcit2oPpfxWe                                                         +=                                                                                                                                       1
        _6s2pxP8Fxy0cKno3NrgIeiF65WOYHH.append(























                                                                                                                                                                                                        _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E




















                                                                                                                                                                                                                                                            )
    return _6s2pxP8Fxy0cKno3NrgIeiF65WOYHH
def _6s2pxP8Fxy0cKno3NrgIeiF65WOYHH(























                                                                                                                                                                                                _QI2atZFwNrUKNkS7c6RDy6Xa7014MR, _CttQ6tHbcklk8pE62XKYDbOeSJluK1




















                                                                                                                                                                                                                                                    ):
    _0ulWv02YpDSKo7HjYBOtHPBLfE9mY0                                                        =                                                                                                  _mh2lIrvtp5H93pf9F1rruMBQggmLDg(























                                                                                                                                                                                                    _QI2atZFwNrUKNkS7c6RDy6Xa7014MR




















                                                                                                                                                                                                                                                        ) 
    _6s2pxP8Fxy0cKno3NrgIeiF65WOYHH                                                        =                                                                                                  []
    for _QHh7QzyXfbMolkEsOw539rMnG9IQml in     _0ulWv02YpDSKo7HjYBOtHPBLfE9mY0:
        _etFjHXefkC51Qgb1TTiCvh5iMyplFg                                                        =                                                                                                  ''
        for _fRCKK0801ssk2Cz1as9z9AEOeCKnSV in         _QHh7QzyXfbMolkEsOw539rMnG9IQml:
            _etFjHXefkC51Qgb1TTiCvh5iMyplFg                                                         +=                                                                                                                                       _vtaTe6YhRPCpqwwSU9BRqkpIZcQ5xt(























                                                                                                                                                                                                            _CttQ6tHbcklk8pE62XKYDbOeSJluK1, str(























                                                                                                                                                                                                                _fRCKK0801ssk2Cz1as9z9AEOeCKnSV




















                                                                                                                                                                                                                                                                    ))
        _6s2pxP8Fxy0cKno3NrgIeiF65WOYHH.append(























                                                                                                                                                                                                        _etFjHXefkC51Qgb1TTiCvh5iMyplFg




















                                                                                                                                                                                                                                                            )
    return _6s2pxP8Fxy0cKno3NrgIeiF65WOYHH
def _3L2XfZmAA6iLMULntLjAf6Cjx0caHA(























                                                                                                                                                                                                _IquFczMzaOkDnP1HRaI7hSD23gy2QJ, _AO5zctYIzp9mrhrtJjkQ6iFDsMopns




















                                                                                                                                                                                                                                                    ):
    _r5TS2kP3VYSqDaFb5boc280coD3rBu                                                        =                                                                                                  _g8vxurv8oI28h5ggfYGUEbaDMktLNM.path.dirname(























                                                                                                                                                                                                    _g8vxurv8oI28h5ggfYGUEbaDMktLNM.path.realpath(























                                                                                                                                                                                                        __file__




















                                                                                                                                                                                                                                                            ))                                                                                                   +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   '\\logs\\'
    _5q11nJyT2AU80OiiGxAhs8XSrLFRjW                                                        =                                                                                                  _AO5zctYIzp9mrhrtJjkQ6iFDsMopns[_AO5zctYIzp9mrhrtJjkQ6iFDsMopns.rfind(























                                                                                                                                                                                                    '/')+1:_AO5zctYIzp9mrhrtJjkQ6iFDsMopns.rfind(























                                                                                                                                                                                                    '.')]
    _pYuOathAB4AOTp4BBoA8jayypHTmfz                                                        =                                                                                                  _9FMlrH7GIQLPHK0NivP799cKP1Ntbx.now(












































                                                                                                                                                                                                                                                        ).strftime(























                                                                                                                                                                                                    "%Y-%m-%d_%H-%M-%S_"                                                                                                   +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   _5q11nJyT2AU80OiiGxAhs8XSrLFRjW                                                                                                   +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ' output_log._mzE5jXyPh0zJEGqEeqGkVruwgp9wQj')
    _Y1fNADk64lMxX594tS27NAnYe2OFKV                                                        =                                                                                                  _g8vxurv8oI28h5ggfYGUEbaDMktLNM.path.join(























                                                                                                                                                                                                    _r5TS2kP3VYSqDaFb5boc280coD3rBu, _pYuOathAB4AOTp4BBoA8jayypHTmfz




















                                                                                                                                                                                                                                                        )
    _Qw2ewXrjGobtT1Wg4EGN48ufmFk4l5                                                        =                                                                                                  _mh2lIrvtp5H93pf9F1rruMBQggmLDg(























                                                                                                                                                                                                    _AO5zctYIzp9mrhrtJjkQ6iFDsMopns




















                                                                                                                                                                                                                                                        )
    _30XqOXFpAqRxKNgG6VlIrmfJwZjCle                                                        =                                                                                                  []
    for _LHeQPgLLUNVv8lwUXLB0hEGTcFD1v4 in     _Qw2ewXrjGobtT1Wg4EGN48ufmFk4l5:
        _30XqOXFpAqRxKNgG6VlIrmfJwZjCle.append(























                                                                                                                                                                                                        ','.join(























                                                                                                                                                                                                            _LHeQPgLLUNVv8lwUXLB0hEGTcFD1v4




















                                                                                                                                                                                                                                                                ).replace(























                                                                                                                                                                                                            ',','; ')




















                                                                                                                                                                                                                                                                )
    _7J2KwPug7QDiLEfiRhseqjZtYESqmv                                                        =                                                                                                  []
    for _b3Q9bROj5pxEa2A6K4QugeFYv6tUNG in     range(























                                                                                                                                                                                                    len(























                                                                                                                                                                                                        _IquFczMzaOkDnP1HRaI7hSD23gy2QJ




















                                                                                                                                                                                                                                                            )):
        _7J2KwPug7QDiLEfiRhseqjZtYESqmv.append(























                                                                                                                                                                                                        (_30XqOXFpAqRxKNgG6VlIrmfJwZjCle[_b3Q9bROj5pxEa2A6K4QugeFYv6tUNG], 
                                            _IquFczMzaOkDnP1HRaI7hSD23gy2QJ[_b3Q9bROj5pxEa2A6K4QugeFYv6tUNG][0],
                                            _IquFczMzaOkDnP1HRaI7hSD23gy2QJ[_b3Q9bROj5pxEa2A6K4QugeFYv6tUNG][1]




















                                                                                                ))
    with open(























                                                                                                                                                                                                    _Y1fNADk64lMxX594tS27NAnYe2OFKV, "w"




















                                                                                                                                                                                                                                                        ) as _Y1fNADk64lMxX594tS27NAnYe2OFKV:
        for _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E in         _7J2KwPug7QDiLEfiRhseqjZtYESqmv:
            _Y1fNADk64lMxX594tS27NAnYe2OFKV.write(























                                                                                                                                                                                                            _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E[0]                                                                                                   +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ','                                                                                                   +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E[1]                                                                                                   +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ','                                                                                                   +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   _H0r4kTwUnNZQH2WzfOtCU0Wn2pSY5E[2]                                                                                                   +                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "\n"




















                                                                                                                                                                                                                                                                )
    return _pYuOathAB4AOTp4BBoA8jayypHTmfz