#!/usr/bin/env
import numpy as _ho7xntih6KphTjhAt2knxQumJehwGY;import scipy.stats as _Y16BBfU7J00g8p4768QAZTaiADJ4ux

_T1U9q0wo18LKfhR0AMPq9YLrPqoiYb = { _Y16BBfU7J00g8p4768QAZTaiADJ4ux.uniform : 'Uniform',_Y16BBfU7J00g8p4768QAZTaiADJ4ux.expon : 'Exponential',_Y16BBfU7J00g8p4768QAZTaiADJ4ux.gamma : 'Gamma',_Y16BBfU7J00g8p4768QAZTaiADJ4ux.dweibull : 'Weibull',_Y16BBfU7J00g8p4768QAZTaiADJ4ux.norm : 'Normal',_Y16BBfU7J00g8p4768QAZTaiADJ4ux.lognorm : 'Logarithmic Normal',_Y16BBfU7J00g8p4768QAZTaiADJ4ux.beta : 'Beta',_Y16BBfU7J00g8p4768QAZTaiADJ4ux.logistic : 'Logistic',_Y16BBfU7J00g8p4768QAZTaiADJ4ux.johnsonsb : 'Johnson SB',_Y16BBfU7J00g8p4768QAZTaiADJ4ux.johnsonsu : 'Johnson SU',_Y16BBfU7J00g8p4768QAZTaiADJ4ux.triang : 'Triangular' }
def wbfWGaaK6svGyGpITX3WoqvmGa7eYF(











                                                                                                                                                                                                                                                                                                                                                                                                                _yRDRoFvFUZFBUcge300LH0ylVeORUR











































































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ):
    _1bfgHnE5jH52wSeHyqYlqZ6mFU82Yq = []
    for _RCcv5EWje5QN2cDZxItFTNDfrgGlJQ in _T1U9q0wo18LKfhR0AMPq9YLrPqoiYb:
        try:
            _VcrINJVxNqHsugr6ZkyXaqBxaP0H1r = _RCcv5EWje5QN2cDZxItFTNDfrgGlJQ.fit(











                                                                                                                                                                                                                                                                                                                                                                                                                            _yRDRoFvFUZFBUcge300LH0ylVeORUR











































































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
            _YzzD7ZgQB0nHfNBTWGLj93Q5slgaCy = _RCcv5EWje5QN2cDZxItFTNDfrgGlJQ.nnlf(











                                                                                                                                                                                                                                                                                                                                                                                                                            _VcrINJVxNqHsugr6ZkyXaqBxaP0H1r, _yRDRoFvFUZFBUcge300LH0ylVeORUR











































































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
            _1bfgHnE5jH52wSeHyqYlqZ6mFU82Yq.append(











                                                                                                                                                                                                                                                                                                                                                                                                                            _YzzD7ZgQB0nHfNBTWGLj93Q5slgaCy











































































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
        except ValueError:
            pass
    
    _mQ8eR0wOw54fE7qqk0HinVoIrWqKbt = [(











                                                                                                                                                                                                                                                                                                                                                                                                                    _RCcv5EWje5QN2cDZxItFTNDfrgGlJQ.name, _YzzD7ZgQB0nHfNBTWGLj93Q5slgaCy











































































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) for _RCcv5EWje5QN2cDZxItFTNDfrgGlJQ, _YzzD7ZgQB0nHfNBTWGLj93Q5slgaCy in zip(











                                                                                                                                                                                                                                                                                                                                                                                                                    _T1U9q0wo18LKfhR0AMPq9YLrPqoiYb, _1bfgHnE5jH52wSeHyqYlqZ6mFU82Yq











































































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )]
    _q2ZV7am7VHIhX1kHXJjFOnFgzDMZs8 = sorted(











                                                                                                                                                                                                                                                                                                                                                                                                                    zip(











                                                                                                                                                                                                                                                                                                                                                                                                                        _T1U9q0wo18LKfhR0AMPq9YLrPqoiYb, _1bfgHnE5jH52wSeHyqYlqZ6mFU82Yq











































































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ), key=lambda d: d[1]











































































                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )[0]
    return _T1U9q0wo18LKfhR0AMPq9YLrPqoiYb[_q2ZV7am7VHIhX1kHXJjFOnFgzDMZs8[0]]
