from PyQt5 import *

class ximqoP7GjZpiLc2jtevhq5zWKiDsbUY(QtWidgets.QWidget):
    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setupUi(self) 
        self.setWindowTitle('Fitness of Statistical Tests Help')
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 550)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-weight:600; color:#000000;\">Input File</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; color:#000000;\">Input should be in the format of a regular expression, followed by the a series of numbers, all of which are space seperated.  </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri Light,sans-serif\'; font-size:9pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; color:#000000;\">Example:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-style:italic; color:#000000;\">A*B* 9 32 2 2.2 91 2</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-style:italic; color:#000000;\">(BA)* 9 1 2 2 2 3.3 5</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-weight:600;\">Regular Expressions</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">The regular expressions listed in the input file are placed in the Regular Expressions windows. You can select them to view various information about the data associated with that regular expression. The left and right windows are identical, when both sides have a regular expression selected, there will be a histogram showing the data for each regular expression.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-weight:600;\">Regular Expression Properties</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">The regular expression properties windows show the results of statistical tests specifically for the regular expression selected above.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">The </span><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-style:italic;\">KS Test Statistic</span><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"> is result of running the One-Sided Kolmogorov Smirnov Normality Test on the data in the selected regular expression, this is not the p-value. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-style:italic;\">P-Value</span><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"> is the p-value derived from the KS Test Statistic, any p-value above 0.05 accepts the null hypothesis that the data comes from a normal distribution, any p-value below 0.05 rejects the null hypothesis. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-style:italic;\">Best Distribution </span><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">is the closest matching distribution from a selected pool of distributions. The selected pool is:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">    - Uniform</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">    - Exponential</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">    - Gamma</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">    - Weibull</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">    - Normal</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">    - Logarithmic Normal</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">    - Beta</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">    - Logistic</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">    - Johnson SB</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">    - Johnson SU</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">    - Triangular </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-style:italic;\">Total Items</span><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"> is the amount of data points in the input file associated with the selected regular expression.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-weight:600;\">Statistical Tests</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">The statistical tests window contains two sections, the Scott Knott test results, and the graphical distribution (along with other data). </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">The graphical distribution window can be activated by selecting a regular expression from the left and right side windows. The regular expressions must both have at least 2 data points to activate the graphing area. A Two-Sided Kolmogorov Smirnov Test is also run between the data in the two regular expressions. Again showing the Kolmogorov-Smirnov Test Statistic, and the resulting P-Value. A run time is also shown for how long it took to run the individual tests (the two-sided tests are not included). You can choose the number of sections in the histogram in the Bins option, once the desired number of sections is written, click Update to update the graph. To view the Scott Knott test results, click the &quot;</span><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-style:italic;\">Scott Knott Results&quot; </span><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">button at the bottom.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">In the Scott Knott page, you can click the &quot;</span><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-style:italic;\">Distributions&quot; </span><span style=\" font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\">button to go back to the previous page. The Scott Knott page shows the results from running the Scott Knott test with all the regular expressions. Regular expressions are categorized into ranks, regular expressions sharing the same rank are grouped together in the Scott Knott test due to having similar data. The means for each regular expression are also shown in this page. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri Light,sans-serif\'; font-size:9pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri Light,sans-serif\'; font-size:9pt; font-weight:600;\"><br /></p></body></html>"))

